### PR TITLE
Three parameters were added

### PR DESCRIPTION
**Pull request by wlhtea**
Added three parameters: prompt, tags, and title. See the website for details and open Custom Mode to see the meaning of the three parameters.
The original prompt has been changed to gptprompt.

```python
from suno import SongsGen
cookie = 'cookie'
i = SongsGen(cookie)
print(i.get_limit_left())
# i.save_songs(gptprompt="a blue cyber dream song", output_dir='./output')
i.save_songs(title="夏天好像不曾离开 Summer Never Left",tags="轻松的R&B, BPM60, 小调, 电吉他、贝斯、键盘和轻鼓, 男性歌手, 深情温暖的夏日风情\n",prompt=
"[Intro]\n(Instrumental)\n\n[Verse 1]\n城市的灯光慢慢亮起，\n夕阳在窗外悄悄退去。\n心中的热情从未减退，\n夏天的回忆，甜蜜温馨。\n\n[Chorus]\n夏天好像不曾离开，\n你的笑容照亮了我的世界。\n在这宁静的夜晚，\n感受自由，和你一起飞翔。\n\n[Verse 2]\n赤脚踏在温暖的沙滩，\n潮水轻拍，和风轻柔相伴。\n每个夏日黄昏都如此宁静，\n你的每一个吻，都是我的信仰。\n\n[Chorus]\n夏天好像不曾离开，\n温暖的怀抱，爱情的味道。\n在这自由的空气中，\n和你共舞，直到时间尽头。\n\n[Bridge]\nSunset fades, but love stays (夕阳消逝，爱永存),\nHand in hand, through endless days (手牵手，穿越无尽的日子).\nIn every breath, in every gaze (在每一次呼吸，每一次凝视),\nOur summer never fades away (我们的夏天永不消逝).\n\n[Outro]\n(Instrumental)", output_dir='./output')
```
or
```python
from suno import SongsGen
i = SongsGen('cookie') # Replace 'cookie'
print(i.get_limit_left())
i.save_songs(gptprompt="a blue cyber dream song") // The default save path is . /output
```

### CODE REVIEW

**Comment by yihong0618** [comment]
@wlhtea This is the same as #7 so we maybe focus on it first.
sorry for that.

**Comment by yihong0618** [comment]
and you upload to the wrong location

**Comment by wlhtea** [comment]
Apologies for not being very familiar with GitHub operations, I'll take care of that in the future, if you need help I can provide it!

**Comment by yihong0618** [comment]
@wlhtea  don't worry I will deal with https://github.com/yihong0618/SunoSongsCreator/pull/7 and merge
then will close yours(which is very sorry)
and I will add you to the co-author when #7 merged is that OK?

thanks very much for your effort

**Comment by wlhtea** [comment]
Ok thanks! Here's my changed [suno.py](https://github.com/wlhtea/SunoSongsCreator/blob/wlhtea-patch-1/suno.py), the user can choose to pass gptprompt or pass three other parameters, it must be noted that I found out that even the other parameter that is not given to a variable should not be None it should be empty.

Modified locations: get_songs and save_songs

**Comment by yihong0618** [comment]
@wlhtea  added closing it thanks

**Pull request closed without merging**
