### PR TITLE
Updated the link address and changed the download logic

### PR DESCRIPTION
**Pull request by buzhia**
Updated the link address and changed the download logic

### CODE REVIEW

**Comment by yihong0618** [comment]
this is not right..
you can try some songs for it cdn is generating after play it or a while time
I tried your way in the first time, but failed most of the songs

**Comment by yihong0618** [comment]
will close this after you try

**Comment by buzhia** [comment]
> this is not right.. you can try some songs for it cdn is generating after play it or a while time I tried your way in the first time, but failed most of the songs
Maybe the network environment is different, I can use the cdn here but can download normally, and the original link often appears dozens of minutes without response

**Comment by yihong0618** [comment]
@buzhia can you reopen it?
I have an idea that we can try cdn first, if not 404 then use cdn?

**Comment by yihong0618** [comment]
I will commit in your pr

**Comment by buzhia** [comment]
> @buzhia can you reopen it? I have an idea that we can try cdn first, if not 404 then use cdn?

image
Accessing the cdn always fails the first time (I remember the code was 403), but it usually downloads normally on the second time

**Comment by yihong0618** [comment]
will test thanks

**Comment by yihong0618** [comment]
can you try your code `python -m suno --prompt 'a big red dream song'`

can work fine?

**Comment by yihong0618** [comment]
sorry its not work in my side so closing it 

image

**Comment by buzhia** [comment]
> sorry its not work in my side so closing it
> 
> image

Got it, I tried it on Tencent Cloud Server

**Comment by buzhia** [comment]
> can you try your code `python -m suno --prompt 'a big red dream song'`
> 
> can work fine?

image
give up this branch~

**Pull request closed without merging**
